eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yunkai123/SpringCloud
          searchPaths: Configs
#          username:
#          password:
  application:
    name: config-server
              